### ISSUE TITLE
Cannot connect to mongo replica set docker

### ISSUE THREAD

**Issue by jagzmz** [idealo/mongodb-slow-operations-profiler#19]
docker compose config

```yml
test:
        image: mongo
        container_name: test
        command: --replSet rs0
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - ./data/mongodb:/data/db
            - ./mongod.conf:/etc/mongod.conf
        ports:
            - 27017:27017
        restart: unless-stopped
```

<detail>
<summary>Profiler Config</summary>

```json
{
    "collector": {
        "hosts": [
            "collector-db:27017"
        ],
        "db": "mongodba",
        "collection": "slowops"
    },
    "profiled": [
        {
            "label": "test-dbs",
            "hosts": [
                "test:27017"
            ],
            "ns": [
                "playground.*"
            ],
            "slowMS": 3000,
            "adminUser": "",
            "adminPw": "",
            "collect": true
        }
    ],
    "yAxisScale": "milliseconds",
    "adminToken": "mySecureAdminToken",
    "defaultSlowMS": 100,
    "defaultResponseTimeoutInMs": 3000,
    "maxWeblogEntries": 100,
    "systemProfileCollectionMaxSizeInMB": 16
}
```
</detail>

```
2022/06/20 12:25:19,075 ProfilingReader for 'test-dbs' at 127.0.0.1:27017/playground will be restarted in 8 seconds due to MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=127.0.0.1:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]
2022/06/20 12:25:44,588 Pool of max. 3 threads to get updated server status is going to be closed after max. response timeout of 3000 ms although not all threads have terminated. Add CPU cores or increment response timeout to solve the issue.
2022/06/20 12:25:44,590 TimeoutException while getting updated server status within 3000 ms for 'test-dbs' at 127.0.0.1:27017/playground
```

**Comment by kagahd** [comment]
There are several things missing. For example you'd need to initialize the replica set by `rs.initate()` before you can start using it. Also, your profiler config uses host names that you didn't define in your docker-compose e.g. `collector-db`.
**Hint:** Start first to connect to your mongodb within a mongoshell. When this works, configure the profiler the same way to connect.

**Comment by jagzmz** [comment]
@kagahd I have replica set already enabled.

Here is the full docker config, previous one was partial

```yml
version: '3.8'


services:
    test:
        image: mongo
        container_name: test
        command: --replSet rs0
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - ./data/mongodb:/data/db
            - ./mongod.conf:/etc/mongod.conf
        ports:
            - 27017:27017
        restart: unless-stopped
    collector-db:
        image: mongo:5.0
        container_name: collector-db
    profiler-webapp:
        build:
            context: .
            dockerfile: Dockerfile-mongo-profiler
        container_name: profiler-webapp
        depends_on:
            - collector-db
            - test
        ports:
            - "8080:8080"
        links:
            - "collector-db"
            - "test"

```

**Comment by kagahd** [comment]
And how do you initialize the replSet?

**Comment by jagzmz** [comment]
I had done it like this 
`rs.initiate({_id:"rs0", members: [{"_id":1, "host":"127.0.0.1:27017"}]})`

**Comment by kagahd** [comment]
Don't use IP addresses, better use hostnames to initialize your replSet. Since you want to profile `test:27017`, the hostname has to be `test`. So, the first lines of your  docker compose should be:

```
version: '3.8'

services:
    test:
        image: mongo
        container_name: test
        hostname: test
``` 
Once started the containers, simply initialize the replSet by  `rs.initiate()`.
